# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbjobbsokerkompetanse
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: veilarbjobbsokerkompetanse/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarbjobbsokerkompetanse/internal/selftest
    initialDay: 20
prometheus:
  enabled: true
  path: veilarbjobbsokerkompetanse/internal/metrics
resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi
fasitResources:
  used:
  - alias: veilarbjobbsokerkompetanseDB
    resourceType: datasource
  - alias: srvveilarbjobbsokerkompetanse
    resourceType: credential
  - alias: securityTokenService
    resourceType: baseUrl
  - alias: Aktoer_v2
    resourceType: webserviceendpoint
  exposed:
  - alias: veilarbjobbsokerkompetanseRS
    resourceType: restservice
    path: /veilarbjobbsokerkompetanse/api