---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbjobbsokerkompetanse
  namespace: default
  labels:
    team: paw
spec:
  env:
  - name: NAV_TRUSTSTORE_KEYSTOREALIAS
    value: na
  - name: VEILARBJOBBSOKERKOMPETANSEDB_OEMENDPOINT
    value: /em/cloud/dbaas/pluggabledbplatforminstance/byrequest/1743
  - name: VEILARBJOBBSOKERKOMPETANSEDB_URL
    value: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=a01dbfl033.adeo.no)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=VEILARBDEMOQ1)(INSTANCE_NAME=ccqf01)(UR=A)(SERVER=DEDICATED)))
  - name: VEILARBJOBBSOKERKOMPETANSEDB_USERNAME
    value: VEILARBDEMO_Q1
  - name: SRVVEILARBJOBBSOKERKOMPETANSE_USERNAME
    value: srvveilarbjobbsoke
  - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
    value: "true"
  - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
    value: NON-PROD
  - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
    value: 5ed4d975-ed5b-40b2-8ac6-9e0c0e61a67e
  - name: APPDYNAMICS_CONTROLLER_HOST_NAME
    value: appdynamics.adeo.no
  - name: APPDYNAMICS_CONTROLLER_PORT
    value: "443"
  - name: SECURITYTOKENSERVICE_URL
    value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
  - name: AKTOER_V2_SECURITYTOKEN
    value: SAML
  - name: AKTOER_V2_ENDPOINTURL
    value: https://app-q1.adeo.no/aktoerregister/ws/Aktoer/v2
  - name: AKTOER_V2_WSDLURL
    value: http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/fim/nav-fim-aktoer-v2-tjenestespesifikasjon/2.0.1/nav-fim-aktoer-v2-tjenestespesifikasjon-2.0.1.zip
  - name: VEILARBOPPFOLGINGAPI_URL
    value: https://veilarboppfolging-q1.nais.preprod.local/veilarboppfolging/api
  - name: ABAC_PDP_ENDPOINT_DESCRIPTION
    value: The XACML JSON Endpoint for evaluating attributes against policies
  - name: ABAC_PDP_ENDPOINT_URL
    value: https://wasapp-q1.adeo.no/asm-pdp/authorize
  - name: AAD_B2C_CLIENTID_USERNAME
    value: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5
  - name: AAD_B2C_DISCOVERY_URL
    value: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
  - name: ISSO_HOST_URL
    value: https://isso-q.adeo.no/isso/oauth2
  - name: ISSO_JWKS_URL
    value: https://isso-q.adeo.no/isso/oauth2/connect/jwk_uri
  - name: ISSO_ISSUER_URL
    value: https://isso-q.adeo.no:443/isso/oauth2
  - name: ISSO_ISALIVE_URL
    value: https://isso-q.adeo.no/isso/isAlive.jsp
  - name: ISSO_RP_USER_USERNAME
    value: veilarblogin-q1
  - name: VEILARBLOGIN_REDIRECT_URL_DESCRIPTION
    value: Login for veilarb
  - name: VEILARBLOGIN_REDIRECT_URL_URL
    value: https://app-q1.adeo.no/veilarblogin/api/login
  image: docker.adeo.no:5000/fo/veilarbjobbsokerkompetanse
  ingresses:
  - https://veilarbjobbsokerkompetanse.nais.preprod.local
  - https://app-q1.adeo.no/veilarbjobbsokerkompetanse
  liveness:
    path: veilarbjobbsokerkompetanse/internal/isAlive
    port: 8080
    initialDelay: 60
  port: 8080
  prometheus:
    enabled: true
    path: veilarbjobbsokerkompetanse/internal/metrics
  readiness:
    path: veilarbjobbsokerkompetanse/internal/isReady
    port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
    - kvPath: /oracle/data/dev/creds/veilarbdemo_q1-user
      mountPath: /var/run/secrets/nais.io/veilarbjobbsokerkompetanseDB
    - kvPath: /serviceuser/data/dev/srvveilarbjobbsokerkompetanse
      mountPath: /var/run/secrets/nais.io/srvveilarbjobbsokerkompetanse
    - kvPath: /kv/preprod/fss/veilarbjobbsokerkompetanse/default
      mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
