---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbjobbsokerkompetanse
  namespace: default
  labels:
    team: paw
spec:
  env:
  - name: NAV_TRUSTSTORE_KEYSTOREALIAS
    value: na
  - name: VEILARBJOBBSOKERKOMPETANSEDB_URL
    value: jdbc:oracle:thin:@a01dbfl037.adeo.no:1521/veilarbjobbsokerkompetanse
  - name: VEILARBJOBBSOKERKOMPETANSEDB_USERNAME
    value: VEILARBJOBBSOKERKOMPETANSE
  - name: SRVVEILARBJOBBSOKERKOMPETANSE_USERNAME
    value: srvveilarbjobbsoke
  - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
    value: PROD
  - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
    value: a2aa3452-c3af-4436-9871-d7d203a8f79f
  - name: APPDYNAMICS_CONTROLLER_HOST_NAME
    value: appdynamics.adeo.no
  - name: APPDYNAMICS_CONTROLLER_PORT
    value: "443"
  - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
    value: "true"
  - name: SECURITYTOKENSERVICE_URL
    value: https://sts.adeo.no/SecurityTokenServiceProvider/
  - name: AKTOER_V2_SECURITYTOKEN
    value: SAML
  - name: AKTOER_V2_ENDPOINTURL
    value: https://app.adeo.no/aktoerregister/ws/Aktoer/v2
  - name: AKTOER_V2_WSDLURL
    value: http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/fim/nav-fim-aktoer-v2-tjenestespesifikasjon/2.0.1/nav-fim-aktoer-v2-tjenestespesifikasjon-2.0.1.zip
  - name: VEILARBOPPFOLGINGAPI_URL
    value: https://veilarboppfolging.nais.adeo.no/veilarboppfolging/api
  - name: ABAC_PDP_ENDPOINT_DESCRIPTION
    value: The XACML JSON Endpoint for evaluating attributes against policies
  - name: ABAC_PDP_ENDPOINT_URL
    value: https://wasapp.adeo.no/asm-pdp/authorize
  - name: AAD_B2C_CLIENTID_USERNAME
    value: 45104d6a-f5bc-4e8c-b352-4bbfc9381f25
  - name: AAD_B2C_DISCOVERY_URL
    value: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
  - name: ISSO_HOST_URL
    value: https://isso.adeo.no/isso/oauth2
  - name: ISSO_JWKS_URL
    value: https://isso.adeo.no/isso/oauth2/connect/jwk_uri
  - name: ISSO_ISSUER_URL
    value: https://isso.adeo.no:443/isso/oauth2
  - name: ISSO_ISALIVE_URL
    value: https://isso.adeo.no/isso/isAlive.jsp
  - name: ISSO_RP_USER_USERNAME
    value: veilarblogin-p
  - name: VEILARBLOGIN_REDIRECT_URL_URL
    value: https://app.adeo.no/veilarblogin/api/login
  image: docker.adeo.no:5000/fo/veilarbjobbsokerkompetanse
  ingresses:
  - https://veilarbjobbsokerkompetanse.nais.adeo.no
  - https://app.adeo.no/veilarbjobbsokerkompetanse
  liveness:
    path: veilarbjobbsokerkompetanse/internal/isAlive
    port: 8080
    initialDelay: 60
  port: 8080
  prometheus:
    enabled: true
    path: veilarbjobbsokerkompetanse/internal/metrics
  readiness:
    path: veilarbjobbsokerkompetanse/internal/isReady
    port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
    - kvPath: /oracle/data/prod/creds/veilarbjobbsokerkompetanse-user
      mountPath: /var/run/secrets/nais.io/veilarbjobbsokerkompetanseDB
    - kvPath: /serviceuser/data/prod/srvveilarbjobbsokerkompetanse
      mountPath: /var/run/secrets/nais.io/srvveilarbjobbsokerkompetanse
    - kvPath: /kv/prod/fss/veilarbjobbsokerkompetanse/default
      mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
