# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbjobbsokerkompetanse
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: veilarbjobbsokerkompetanse/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarbjobbsokerkompetanse/internal/selftest
    initialDay: 20
fasitResources:
  used:
  - alias: veilarbjobbsokerkompetanseDB
    resourceType: datasource
  - alias: srvveilarbjobbsokerkompetanse
    resourceType: credential
  - alias: securityTokenService
    resourceType: baseUrl
  - alias: Aktoer_v2
    resourceType: webserviceendpoint
  - alias: app_truststore
    resourceType: certificate
  exposed:
  - alias: veilarbjobbsokerkompetanseRS
    resourceType: restservice
    path: /jobbsokerkompetanse/rs
  - alias: veilarbjobbsokerkompetanseWS
    resourceType: webserviceendpoint
    path: /jobbsokerkompetanse/ws
    wsdlGroupId: no.nav.tjenester
    wsdlArtifactId: brukerdialog-jobbsokerkompetanse-v1-tjenestespesifikasjon
    wsdlVersion: 1.0.1
    securityToken: SAML